### ISSUE TITLE
Grid Request

### ISSUE THREAD

**Issue by mcironlung** [bittiez/ClassicUO#12]
Grid bag request 1: It would be helpful to toggle into grid bag mode from an icon on the default bag as well.  This helps with sorting a bag for a vendor so other non-grid players can still items.

Grid bag request 2: Can the closed state of a bag be saved?  For example, everything opens in the grid the first time it’s opened, then if a certain bag (like a vendor or a sorted chest) is toggled to the default bag view, it stays in that view until toggled back into the grid.

**Comment by elderwyn** [comment]
PR - https://github.com/bittiez/ClassicUO/pull/15

![vendor](https://user-images.githubusercontent.com/127065794/223243324-22aaaac3-677b-4c3f-af00-0840d5284f04.gif)

**Comment by bittiez** [comment]
So as for number 1, I like the idea, however I don't want to modify CUO's classic gump's, I'm trying to keep this fairly close to original CUO as possible

And as for number 2 I also like the idea of saving this, but the issue lies in that it would require the client to basically save the state of every container you open which would eventually be an issue.. I suppose you could possible add a date to each saved contaienr state and after xx of days remove it from the saved data, I will keep this in mind but won't promise anything yet

**Comment by bittiez** [comment]
As an alternative I'm working on player vendors opening both grid and regular containers [vendor-packs](https://github.com/bittiez/ClassicUO/tree/vendor-packs)

**Comment by bittiez** [comment]
Vendors now open both grid and regular containers(as an alternative)
